//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Logger_Entities : DbContext
    {
        public Logger_Entities()
            : base("name=Logger_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<LogEntry> LogEntries { get; set; }
        public virtual DbSet<LogEntryArchive> LogEntryArchives { get; set; }
        public virtual DbSet<LogPayload> LogPayloads { get; set; }
        public virtual DbSet<LogPayloadArchive> LogPayloadArchives { get; set; }
        public virtual DbSet<LogType> LogTypes { get; set; }
        public virtual DbSet<LogsDetail> LogsDetails { get; set; }
    
        public virtual int ArchiveLogs(Nullable<int> archiveDays)
        {
            var archiveDaysParameter = archiveDays.HasValue ?
                new ObjectParameter("ArchiveDays", archiveDays) :
                new ObjectParameter("ArchiveDays", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ArchiveLogs", archiveDaysParameter);
        }
    }
}
