//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsDetail
    {
        public int LogId { get; set; }
        public int ClientId { get; set; }
        public int ApplicationId { get; set; }
        public int LogType { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string ApplicationName { get; set; }
        public string ClientName { get; set; }
        public string LogTypeName { get; set; }
    }
}
