//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogEntry()
        {
            this.LogPayloads = new HashSet<LogPayload>();
        }
    
        public int LogId { get; set; }
        public int ClientId { get; set; }
        public int ApplicationId { get; set; }
        public int LogType { get; set; }
        public System.DateTime LogDateTime { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPayload> LogPayloads { get; set; }
    }
}
